name: pgc_app
description: Application de gestion de club de sport de combat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # HTTP
  http: ^1.2.1
  # Stockage local du JWT
  flutter_secure_storage: ^9.0.0
  # Gestion d'état
  provider: ^6.1.2
  # Navigation
  go_router: ^13.2.0
  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true