name: pgc_app
description: Application de gestion de club de sport de combat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # HTTP
  http: ^1.2.1
  # Stockage local du JWT
  flutter_secure_storage: ^9.0.0
  # Gestion d'état
  provider: ^6.1.2
  # Navigation
  go_router: ^13.2.0
  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  # Upload photo
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/coaches/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/PGC_logo_app.png"
  min_sdk_android: 21

flutter_icons:
  android: true
  ios: true

  image_path: "assets/icon.png"

  adaptive_icon_background: "#0F2A1D"   # vert PGC (ou couleur de fond)
  adaptive_icon_foreground: "assets/icon_foreground.png"