// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCWcR610xdkRAj6gLzTpnjlWgBC2oNUk',
    appId: '1:218869625375:web:b02c94e74c1354472c9b2a',
    messagingSenderId: '218869625375',
    projectId: 'pgc-app-c4f8a',
    authDomain: 'pgc-app-c4f8a.firebaseapp.com',
    storageBucket: 'pgc-app-c4f8a.firebasestorage.app',
    measurementId: 'G-H6RTYEKLZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40jKDPj7gghKBmJBIfT2k7ncjxz2iFEs',
    appId: '1:218869625375:android:564b9a4f09363a1a2c9b2a',
    messagingSenderId: '218869625375',
    projectId: 'pgc-app-c4f8a',
    storageBucket: 'pgc-app-c4f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAucxnSlxW2PYq5I6I4Vz0CfcVvjeCCW-E',
    appId: '1:218869625375:ios:048b795822b54b4d2c9b2a',
    messagingSenderId: '218869625375',
    projectId: 'pgc-app-c4f8a',
    storageBucket: 'pgc-app-c4f8a.firebasestorage.app',
    iosBundleId: 'com.pgcapp.pgcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAucxnSlxW2PYq5I6I4Vz0CfcVvjeCCW-E',
    appId: '1:218869625375:ios:048b795822b54b4d2c9b2a',
    messagingSenderId: '218869625375',
    projectId: 'pgc-app-c4f8a',
    storageBucket: 'pgc-app-c4f8a.firebasestorage.app',
    iosBundleId: 'com.pgcapp.pgcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKCWcR610xdkRAj6gLzTpnjlWgBC2oNUk',
    appId: '1:218869625375:web:64c980e88108fb2c2c9b2a',
    messagingSenderId: '218869625375',
    projectId: 'pgc-app-c4f8a',
    authDomain: 'pgc-app-c4f8a.firebaseapp.com',
    storageBucket: 'pgc-app-c4f8a.firebasestorage.app',
    measurementId: 'G-WMF0RP0HDG',
  );
}
